name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  test-swift:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12.5
        run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - name: Run tests
        run: make test-swift
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-linux
